### ISSUE TITLE
Invalid literal

### ISSUE THREAD

**Issue by AllanJard** [divertingPan/video_scanner#1]
Hi,

I'd love to get this going for some videos of locos I've taken myself. I download and have run the linux version (0.3.4) and run it. It shows the GUI and I give it the source file, position, images saving width, start frame and sensitivity. Then I click "calculate move" but it shows an error "Error: invalid literal for int() with base 10: ''`.

![image](https://github.com/divertingPan/video_scanner/assets/84905443/72e621d2-5ba8-4693-a71c-7edddf7e3e44)

Any idea what is causing the issue?

**Comment by divertingPan** [comment]
Hi, 
You should fill in the `mask y_top, y_bottom, x_left, x_right` as well. And then click `calculate move`. 
After that, the `segment width` and `position (frame)` should be filled automatically. 
Then you can click `process` to generate your images, or adjust the values in any of the textbox to get a better result.

The parameters and the function previews are shown as follows: 
https://github.com/divertingPan/video_scanner/blob/main/img/ver_0.3.3.png

Please leave a message if there's any further question. 
Cheers

**Comment by AllanJard** [comment]
Thanks for the mega fast reply! If I fill in the mask parameters I get a different error

> Error: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

![image](https://github.com/divertingPan/video_scanner/assets/84905443/bc693d17-dbca-4262-be05-ce94561d014c)

**Comment by divertingPan** [comment]
Hi, 
The possible reason is the optical flow fails to detected. You can check the range of mask. Make sure it covers the moving object. 
Especially in the first detection frame (`start frame`), the object should appear in this frame.

**Comment by AllanJard** [comment]
Getting closer! Thanks! That populates values into the segment width and position frame.

![image](https://github.com/divertingPan/video_scanner/assets/84905443/1a0da578-41b5-4ee1-a41e-4254c3efdd97)

Now when I click "Process" I get an error shown on the terminal I'm running the python program from:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1921, in __call__
  File "main_ver_0.3.4.py", line 470, in process
  File "main_ver_0.3.4.py", line 532, in save_img
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:1109: error: (-215:Assertion failed) !image.empty() in function 'imencod
```

It does create the directory for output, but there is nothing in it.

**Comment by divertingPan** [comment]
Hi, 
it seems that no moving is detected (all the segment width values are 0). 
For this reason you can check whether the mask is covered with most moving area (try to make the mask larger), or check if the video is too blurry. 
And I updated an example of the splitting width and position. You can even try to manually adjust the `segment width` and `position (frame)` if automated detection is not working. 

![](https://github.com/divertingPan/video_scanner/raw/main/img/parameters.png)

**Comment by AllanJard** [comment]
[This is the video](https://www.dropbox.com/s/s408jtop0dyge0f/20230604_140831.mp4?dl=0) I'm currently working on. It isn't a high quality video, so perhaps that is part of the issue.

If I set it to "manual" and a 16px width, that seems to help. I get a nice looking image out of that.

**Comment by divertingPan** [comment]
Yes, if the automated method is not working, it is better to use manual parameters. 
The automated detection is mainly used to deal with the long, accelerant train. 
Moreover, I noticed your chosen video is not stable (hand shaking), maybe causing the horizonal distortion of the result.

**Comment by AllanJard** [comment]
Yeah - I saw that from the output as well. I'm taking my tripod next time!

This is brilliant - thanks so much for making this software available and for your support of it. I'm going to really enjoy making images with it.

I'm going to close this issue since it was more of a problem with my understanding than anything else :-)
